export default {
    extends: ['@commitlint/config-conventional'],
    rules: {
        'type-empty': [0],
        'subject-empty': [0],
        'subject-full-stop': [0],
        'body-leading-blank': [0],
        'type-enum': [
            2,
            'always',
            [
                'feat',
                'fix',
                'docs',
                'style',
                'refactor',
                'perf',
                'test',
                'build',
                'ci',
                'chore',
                'revert',
                'wip',
            ],
        ],
        'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
        'subject-max-length': [2, 'always', 4000],
        'body-max-line-length': [2, 'always', 4000],
        'header-max-length': [2, 'always', 4000],
    },
}
