- op: replace
  path: /spec/rules/0/host
  value: app.staging.yourdomain.com
- op: replace
  path: /spec/rules/1/host
  value: api.staging.yourdomain.com
- op: replace
  path: /spec/rules/2/host
  value: convex-api.staging.yourdomain.com
- op: replace
  path: /spec/rules/3/host
  value: convex-site.staging.yourdomain.com
- op: replace
  path: /spec/rules/4/host
  value: convex-dashboard.staging.yourdomain.com
