/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsofserviceRouteImport } from './routes/termsofservice'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacystatementRouteImport } from './routes/privacystatement'
import { Route as MeRouteImport } from './routes/me'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as SurveysIndexRouteImport } from './routes/surveys/index'
import { Route as StandupsIndexRouteImport } from './routes/standups/index'
import { Route as RetrosIndexRouteImport } from './routes/retros/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PollsIndexRouteImport } from './routes/polls/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as IcebreakersIndexRouteImport } from './routes/icebreakers/index'
import { Route as EstimateIndexRouteImport } from './routes/estimate/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as SurveysSurveyIdRouteImport } from './routes/surveys/$surveyId'
import { Route as StandupsNewRouteImport } from './routes/standups/new'
import { Route as StandupsStandupIdRouteImport } from './routes/standups/$standupId'
import { Route as RetrosNewRouteImport } from './routes/retros/new'
import { Route as RetrosRetroIdRouteImport } from './routes/retros/$retroId'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileSessionsRouteImport } from './routes/profile/sessions'
import { Route as ProfileSecurityRouteImport } from './routes/profile/security'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations/$orgId'
import { Route as IcebreakersNewRouteImport } from './routes/icebreakers/new'
import { Route as IcebreakersSessionIdRouteImport } from './routes/icebreakers/$sessionId'
import { Route as EstimateNewRouteImport } from './routes/estimate/new'
import { Route as EstimateSessionIdRouteImport } from './routes/estimate/$sessionId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSessionsRouteImport } from './routes/dashboard/sessions'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard/security'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMeRouteImport } from './routes/dashboard/me'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSocialCallbackRouteImport } from './routes/auth/social-callback'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth/accept-invite'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminTeamRolesRouteImport } from './routes/admin/team-roles'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminOrgSetupRouteImport } from './routes/admin/org-setup'
import { Route as AdminConvexRouteImport } from './routes/admin/convex'

const TermsofserviceRoute = TermsofserviceRouteImport.update({
  id: '/termsofservice',
  path: '/termsofservice',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacystatementRoute = PrivacystatementRouteImport.update({
  id: '/privacystatement',
  path: '/privacystatement',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIndexRoute = SurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandupsIndexRoute = StandupsIndexRouteImport.update({
  id: '/standups/',
  path: '/standups/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosIndexRoute = RetrosIndexRouteImport.update({
  id: '/retros/',
  path: '/retros/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PollsIndexRoute = PollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IcebreakersIndexRoute = IcebreakersIndexRouteImport.update({
  id: '/icebreakers/',
  path: '/icebreakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateIndexRoute = EstimateIndexRouteImport.update({
  id: '/estimate/',
  path: '/estimate/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSurveyIdRoute = SurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const StandupsNewRoute = StandupsNewRouteImport.update({
  id: '/standups/new',
  path: '/standups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StandupsStandupIdRoute = StandupsStandupIdRouteImport.update({
  id: '/standups/$standupId',
  path: '/standups/$standupId',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosNewRoute = RetrosNewRouteImport.update({
  id: '/retros/new',
  path: '/retros/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosRetroIdRoute = RetrosRetroIdRouteImport.update({
  id: '/retros/$retroId',
  path: '/retros/$retroId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSessionsRoute = ProfileSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProfileRoute,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const IcebreakersNewRoute = IcebreakersNewRouteImport.update({
  id: '/icebreakers/new',
  path: '/icebreakers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IcebreakersSessionIdRoute = IcebreakersSessionIdRouteImport.update({
  id: '/icebreakers/$sessionId',
  path: '/icebreakers/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateNewRoute = EstimateNewRouteImport.update({
  id: '/estimate/new',
  path: '/estimate/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateSessionIdRoute = EstimateSessionIdRouteImport.update({
  id: '/estimate/$sessionId',
  path: '/estimate/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeRoute = DashboardMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSocialCallbackRoute = AuthSocialCallbackRouteImport.update({
  id: '/social-callback',
  path: '/social-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRolesRoute = AdminTeamRolesRouteImport.update({
  id: '/team-roles',
  path: '/team-roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgSetupRoute = AdminOrgSetupRouteImport.update({
  id: '/org-setup',
  path: '/org-setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConvexRoute = AdminConvexRouteImport.update({
  id: '/convex',
  path: '/convex',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/me': typeof MeRoute
  '/privacystatement': typeof PrivacystatementRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reports': typeof ReportsRoute
  '/templates': typeof TemplatesRoute
  '/termsofservice': typeof TermsofserviceRoute
  '/admin/convex': typeof AdminConvexRoute
  '/admin/org-setup': typeof AdminOrgSetupRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/team-roles': typeof AdminTeamRolesRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/social-callback': typeof AuthSocialCallbackRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/me': typeof DashboardMeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/estimate/$sessionId': typeof EstimateSessionIdRoute
  '/estimate/new': typeof EstimateNewRoute
  '/icebreakers/$sessionId': typeof IcebreakersSessionIdRoute
  '/icebreakers/new': typeof IcebreakersNewRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/sessions': typeof ProfileSessionsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/standups/$standupId': typeof StandupsStandupIdRoute
  '/standups/new': typeof StandupsNewRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/estimate/': typeof EstimateIndexRoute
  '/icebreakers/': typeof IcebreakersIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/polls/': typeof PollsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/retros/': typeof RetrosIndexRoute
  '/standups/': typeof StandupsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/me': typeof MeRoute
  '/privacystatement': typeof PrivacystatementRoute
  '/reports': typeof ReportsRoute
  '/templates': typeof TemplatesRoute
  '/termsofservice': typeof TermsofserviceRoute
  '/admin/convex': typeof AdminConvexRoute
  '/admin/org-setup': typeof AdminOrgSetupRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/team-roles': typeof AdminTeamRolesRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/social-callback': typeof AuthSocialCallbackRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/me': typeof DashboardMeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/estimate/$sessionId': typeof EstimateSessionIdRoute
  '/estimate/new': typeof EstimateNewRoute
  '/icebreakers/$sessionId': typeof IcebreakersSessionIdRoute
  '/icebreakers/new': typeof IcebreakersNewRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/sessions': typeof ProfileSessionsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/standups/$standupId': typeof StandupsStandupIdRoute
  '/standups/new': typeof StandupsNewRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/estimate': typeof EstimateIndexRoute
  '/icebreakers': typeof IcebreakersIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/polls': typeof PollsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/retros': typeof RetrosIndexRoute
  '/standups': typeof StandupsIndexRoute
  '/surveys': typeof SurveysIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/me': typeof MeRoute
  '/privacystatement': typeof PrivacystatementRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reports': typeof ReportsRoute
  '/templates': typeof TemplatesRoute
  '/termsofservice': typeof TermsofserviceRoute
  '/admin/convex': typeof AdminConvexRoute
  '/admin/org-setup': typeof AdminOrgSetupRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/team-roles': typeof AdminTeamRolesRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/social-callback': typeof AuthSocialCallbackRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/me': typeof DashboardMeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/estimate/$sessionId': typeof EstimateSessionIdRoute
  '/estimate/new': typeof EstimateNewRoute
  '/icebreakers/$sessionId': typeof IcebreakersSessionIdRoute
  '/icebreakers/new': typeof IcebreakersNewRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/sessions': typeof ProfileSessionsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/standups/$standupId': typeof StandupsStandupIdRoute
  '/standups/new': typeof StandupsNewRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/estimate/': typeof EstimateIndexRoute
  '/icebreakers/': typeof IcebreakersIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/polls/': typeof PollsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/retros/': typeof RetrosIndexRoute
  '/standups/': typeof StandupsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/me'
    | '/privacystatement'
    | '/profile'
    | '/reports'
    | '/templates'
    | '/termsofservice'
    | '/admin/convex'
    | '/admin/org-setup'
    | '/admin/organizations'
    | '/admin/team-roles'
    | '/admin/templates'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/social-callback'
    | '/auth/verify-email'
    | '/dashboard/me'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/estimate/$sessionId'
    | '/estimate/new'
    | '/icebreakers/$sessionId'
    | '/icebreakers/new'
    | '/organizations/$orgId'
    | '/profile/security'
    | '/profile/sessions'
    | '/profile/settings'
    | '/retros/$retroId'
    | '/retros/new'
    | '/standups/$standupId'
    | '/standups/new'
    | '/surveys/$surveyId'
    | '/teams/$teamId'
    | '/admin/'
    | '/dashboard/'
    | '/estimate/'
    | '/icebreakers/'
    | '/organizations/'
    | '/polls/'
    | '/profile/'
    | '/retros/'
    | '/standups/'
    | '/surveys/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/me'
    | '/privacystatement'
    | '/reports'
    | '/templates'
    | '/termsofservice'
    | '/admin/convex'
    | '/admin/org-setup'
    | '/admin/organizations'
    | '/admin/team-roles'
    | '/admin/templates'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/social-callback'
    | '/auth/verify-email'
    | '/dashboard/me'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/estimate/$sessionId'
    | '/estimate/new'
    | '/icebreakers/$sessionId'
    | '/icebreakers/new'
    | '/organizations/$orgId'
    | '/profile/security'
    | '/profile/sessions'
    | '/profile/settings'
    | '/retros/$retroId'
    | '/retros/new'
    | '/standups/$standupId'
    | '/standups/new'
    | '/surveys/$surveyId'
    | '/teams/$teamId'
    | '/admin'
    | '/dashboard'
    | '/estimate'
    | '/icebreakers'
    | '/organizations'
    | '/polls'
    | '/profile'
    | '/retros'
    | '/standups'
    | '/surveys'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/me'
    | '/privacystatement'
    | '/profile'
    | '/reports'
    | '/templates'
    | '/termsofservice'
    | '/admin/convex'
    | '/admin/org-setup'
    | '/admin/organizations'
    | '/admin/team-roles'
    | '/admin/templates'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/social-callback'
    | '/auth/verify-email'
    | '/dashboard/me'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/estimate/$sessionId'
    | '/estimate/new'
    | '/icebreakers/$sessionId'
    | '/icebreakers/new'
    | '/organizations/$orgId'
    | '/profile/security'
    | '/profile/sessions'
    | '/profile/settings'
    | '/retros/$retroId'
    | '/retros/new'
    | '/standups/$standupId'
    | '/standups/new'
    | '/surveys/$surveyId'
    | '/teams/$teamId'
    | '/admin/'
    | '/dashboard/'
    | '/estimate/'
    | '/icebreakers/'
    | '/organizations/'
    | '/polls/'
    | '/profile/'
    | '/retros/'
    | '/standups/'
    | '/surveys/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  MeRoute: typeof MeRoute
  PrivacystatementRoute: typeof PrivacystatementRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsofserviceRoute: typeof TermsofserviceRoute
  EstimateSessionIdRoute: typeof EstimateSessionIdRoute
  EstimateNewRoute: typeof EstimateNewRoute
  IcebreakersSessionIdRoute: typeof IcebreakersSessionIdRoute
  IcebreakersNewRoute: typeof IcebreakersNewRoute
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
  RetrosRetroIdRoute: typeof RetrosRetroIdRoute
  RetrosNewRoute: typeof RetrosNewRoute
  StandupsStandupIdRoute: typeof StandupsStandupIdRoute
  StandupsNewRoute: typeof StandupsNewRoute
  SurveysSurveyIdRoute: typeof SurveysSurveyIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  EstimateIndexRoute: typeof EstimateIndexRoute
  IcebreakersIndexRoute: typeof IcebreakersIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PollsIndexRoute: typeof PollsIndexRoute
  RetrosIndexRoute: typeof RetrosIndexRoute
  StandupsIndexRoute: typeof StandupsIndexRoute
  SurveysIndexRoute: typeof SurveysIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termsofservice': {
      id: '/termsofservice'
      path: '/termsofservice'
      fullPath: '/termsofservice'
      preLoaderRoute: typeof TermsofserviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacystatement': {
      id: '/privacystatement'
      path: '/privacystatement'
      fullPath: '/privacystatement'
      preLoaderRoute: typeof PrivacystatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/': {
      id: '/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof SurveysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standups/': {
      id: '/standups/'
      path: '/standups'
      fullPath: '/standups/'
      preLoaderRoute: typeof StandupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/': {
      id: '/retros/'
      path: '/retros'
      fullPath: '/retros/'
      preLoaderRoute: typeof RetrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/polls/': {
      id: '/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof PollsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icebreakers/': {
      id: '/icebreakers/'
      path: '/icebreakers'
      fullPath: '/icebreakers/'
      preLoaderRoute: typeof IcebreakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/': {
      id: '/estimate/'
      path: '/estimate'
      fullPath: '/estimate/'
      preLoaderRoute: typeof EstimateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId': {
      id: '/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/surveys/$surveyId'
      preLoaderRoute: typeof SurveysSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standups/new': {
      id: '/standups/new'
      path: '/standups/new'
      fullPath: '/standups/new'
      preLoaderRoute: typeof StandupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standups/$standupId': {
      id: '/standups/$standupId'
      path: '/standups/$standupId'
      fullPath: '/standups/$standupId'
      preLoaderRoute: typeof StandupsStandupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/new': {
      id: '/retros/new'
      path: '/retros/new'
      fullPath: '/retros/new'
      preLoaderRoute: typeof RetrosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/$retroId': {
      id: '/retros/$retroId'
      path: '/retros/$retroId'
      fullPath: '/retros/$retroId'
      preLoaderRoute: typeof RetrosRetroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/sessions': {
      id: '/profile/sessions'
      path: '/sessions'
      fullPath: '/profile/sessions'
      preLoaderRoute: typeof ProfileSessionsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icebreakers/new': {
      id: '/icebreakers/new'
      path: '/icebreakers/new'
      fullPath: '/icebreakers/new'
      preLoaderRoute: typeof IcebreakersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icebreakers/$sessionId': {
      id: '/icebreakers/$sessionId'
      path: '/icebreakers/$sessionId'
      fullPath: '/icebreakers/$sessionId'
      preLoaderRoute: typeof IcebreakersSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/new': {
      id: '/estimate/new'
      path: '/estimate/new'
      fullPath: '/estimate/new'
      preLoaderRoute: typeof EstimateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/$sessionId': {
      id: '/estimate/$sessionId'
      path: '/estimate/$sessionId'
      fullPath: '/estimate/$sessionId'
      preLoaderRoute: typeof EstimateSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions': {
      id: '/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/me': {
      id: '/dashboard/me'
      path: '/me'
      fullPath: '/dashboard/me'
      preLoaderRoute: typeof DashboardMeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/social-callback': {
      id: '/auth/social-callback'
      path: '/social-callback'
      fullPath: '/auth/social-callback'
      preLoaderRoute: typeof AuthSocialCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team-roles': {
      id: '/admin/team-roles'
      path: '/team-roles'
      fullPath: '/admin/team-roles'
      preLoaderRoute: typeof AdminTeamRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/org-setup': {
      id: '/admin/org-setup'
      path: '/org-setup'
      fullPath: '/admin/org-setup'
      preLoaderRoute: typeof AdminOrgSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/convex': {
      id: '/admin/convex'
      path: '/convex'
      fullPath: '/admin/convex'
      preLoaderRoute: typeof AdminConvexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConvexRoute: typeof AdminConvexRoute
  AdminOrgSetupRoute: typeof AdminOrgSetupRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminTeamRolesRoute: typeof AdminTeamRolesRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConvexRoute: AdminConvexRoute,
  AdminOrgSetupRoute: AdminOrgSetupRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminTeamRolesRoute: AdminTeamRolesRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSocialCallbackRoute: typeof AuthSocialCallbackRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSocialCallbackRoute: AuthSocialCallbackRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardMeRoute: typeof DashboardMeRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMeRoute: DashboardMeRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProfileRouteChildren {
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileSessionsRoute: typeof ProfileSessionsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileSessionsRoute: ProfileSessionsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  MeRoute: MeRoute,
  PrivacystatementRoute: PrivacystatementRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ReportsRoute: ReportsRoute,
  TemplatesRoute: TemplatesRoute,
  TermsofserviceRoute: TermsofserviceRoute,
  EstimateSessionIdRoute: EstimateSessionIdRoute,
  EstimateNewRoute: EstimateNewRoute,
  IcebreakersSessionIdRoute: IcebreakersSessionIdRoute,
  IcebreakersNewRoute: IcebreakersNewRoute,
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
  RetrosRetroIdRoute: RetrosRetroIdRoute,
  RetrosNewRoute: RetrosNewRoute,
  StandupsStandupIdRoute: StandupsStandupIdRoute,
  StandupsNewRoute: StandupsNewRoute,
  SurveysSurveyIdRoute: SurveysSurveyIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  EstimateIndexRoute: EstimateIndexRoute,
  IcebreakersIndexRoute: IcebreakersIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PollsIndexRoute: PollsIndexRoute,
  RetrosIndexRoute: RetrosIndexRoute,
  StandupsIndexRoute: StandupsIndexRoute,
  SurveysIndexRoute: SurveysIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
