apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retro-tool-ingress
  namespace: retro-tool
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
spec:
  ingressClassName: nginx
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retro-tool-ui
                port:
                  number: 80
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retro-tool-api
                port:
                  number: 8000
    - host: convex-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: convex-backend-api
                port:
                  number: 3210
    - host: convex-site.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: convex-backend-site
                port:
                  number: 3211
    - host: convex-dashboard.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: convex-dashboard
                port:
                  number: 6791